---
kind: pipeline
type: docker
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --recursive --init

- name: first build
  image: theembeddedkitchen/ecp5-toolchain:latest
  recursive: true
  commands:
  - export PATH=/opt/fpga_toolchain/ecp5-toolchain-linux_x86_64-v1.5.1/:$PATH
  - cd soc/
  - RISCV_TOOLCHAIN_PREFIX=riscv64-unknown-elf- make soc.bit
